-- Organizations, memberships, and depot tenancy.
--
-- Static reference tables organizations and organization_users (later renamed
-- user_organizations) live exclusively in Supabase (`pools.static`).  This
-- TimescaleDB migration previously created shadow copies that were never
-- populated in production; those shadows are retired here.  Migrations
-- 024_rename_organization_users and 029_remove_static_shadows are no-ops on
-- fresh databases as a result.
--
-- Idempotent no-op.
DO $$ BEGIN END $$;
